name: Deploy Portfolio

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install and Build
        # Wir sagen dem Runner mit 'working-directory', 
        # dass er in den Unterordner gehen soll
        working-directory: ./portfolio-site
        run: |
          npm install
          npm run build-only

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Der Pfad zum fertigen Build ist nun auch im Unterordner
          path: portfolio-site/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
